### ISSUE TITLE
ImportError: cannot import name Client

### ISSUE THREAD

**Issue by AwdotiaRomanowna** [niqdev/packtpub-crawler#68]
Hi,
I cannot run the script because of import error:
python script/spider.py -c config/prod.cfg -t pdf --notify None
Traceback (most recent call last):
  File "script/spider.py", line 12, in <module>
    from notify import Notify, SERVICE_GMAIL, SERVICE_IFTTT, SERVICE_JOIN, SERVICE_PUSHOVER
  File "/home/boria/repos/test/packtpub-crawler/script/notify.py", line 5, in <module>
    from notification.mypushover import Pushover
  File "/home/boria/repos/test/packtpub-crawler/script/notification/mypushover.py", line 3, in <module>
    from notification.mypushover import Client
ImportError: cannot import name Client

**Comment by niqdev** [comment]
Hi, can you please confirm you are using python 2.x and you run `pip install -r requirements.txt`? thanks

**Comment by hactrox** [comment]
It seems you installed the wrong package `pushover` . You can run `pip uninstall pushover`, and then run `pip install -r requirements.txt`.
