### ISSUE TITLE
Errors upon executing script

### ISSUE THREAD

**Issue by ApCoder123** [niqdev/packtpub-crawler#77]
I have cloned the repository and installed all of the dependencies, but I am getting several errors upon running the following in command line:
`>>C:\Python27\python.exe C:\Users\****\*******\my_ebooks\PACKTPUB_CRAWLER\packtpub-crawler\script\spider.py --config C:\Users\****\*******\my_ebooks\PACKTPUB_CRAWLER\packtpub-crawler\config\prod_example.cfg`

The Errors I'm getting are:
```
Traceback (most recent call last):
  File "C:\Users\****\*******\my_ebooks\PACKTPUB_CRAWLER\packtpub-crawler\script\spider.py", line 9, in <module>
    from upload import Upload, SERVICE_GOOGLE_DRIVE, SERVICE_ONEDRIVE, SERVICE_DROPBOX, SERVICE_SCP
  File "C:\Users\****\*******\my_ebooks\PACKTPUB_CRAWLER\packtpub-crawler\script\upload.py", line 1, in <module>
    from googledrive import GoogleDrive
  File "C:\Users\****\*******\my_ebooks\PACKTPUB_CRAWLER\packtpub-crawler\script\googledrive.py", line 6, in <module>
    import magic
  File "build\bdist.win-amd64\egg\magic.py", line 176, in <module>
ImportError: failed to find libmagic.  Check your installation
```
I'm using the prod_example.cfg file as my config file and I have changed the email and password values in it

**Comment by niqdev** [comment]
Hi, have a look at #33
