### ISSUE TITLE
ImportError: No module named oauth2client.client

### ISSUE THREAD

**Issue by xzl2021** [niqdev/packtpub-crawler#81]
I used `pip install -r requirements.txt` first.
```
root@Ubuntu:~/packtpub-crawler# pip install -r requirements.txt
Requirement already satisfied: APScheduler==3.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: beautifulsoup4==4.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: clint==0.5.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: google-api-python-client==1.3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: html5lib==0.9999999 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: oauth2client==1.4.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: python-magic==0.4.11 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: requests==2.10.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: termcolor==1.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: urllib3==1.15.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: python-firebase==1.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: paramiko==2.0.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: cryptography==1.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: scp==0.10.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: onedrivesdk==1.1.8 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already satisfied: python-pushover==0.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: funcsigs; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: pytz in /usr/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: futures; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.1.0->-r requirements.txt (line 1))
Requirement already satisfied: args in /usr/local/lib/python2.7/dist-packages (from clint==0.5.1->-r requirements.txt (line 3))
Requirement already satisfied: httplib2>=0.8 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client==1.3.2->-r requirements.txt (line 4))
Requirement already satisfied: uritemplate>=0.6 in /usr/local/lib/python2.7/dist-packages/uritemplate-3.0.0-py2.7.egg (from google-api-python-client==1.3.2->-r requirements.txt (line 4))
Requirement already satisfied: rsa==3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.4.11->-r requirements.txt (line 6))
Requirement already satisfied: pyasn1==0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.4.11->-r requirements.txt (line 6))
Requirement already satisfied: pyasn1-modules==0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client==1.4.11->-r requirements.txt (line 6))
Requirement already satisfied: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography==1.6->-r requirements.txt (line 13))
Requirement already satisfied: enum34 in /usr/lib/python2.7/dist-packages (from cryptography==1.6->-r requirements.txt (line 13))
Requirement already satisfied: idna>=2.0 in /usr/lib/python2.7/dist-packages (from cryptography==1.6->-r requirements.txt (line 13))
Requirement already satisfied: ipaddress in /usr/lib/python2.7/dist-packages (from cryptography==1.6->-r requirements.txt (line 13))
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->cryptography==1.6->-r requirements.txt (line 13))
```

And setup my prod.cfg file.
But when I used `python script/spider.py -c config/prod.cfg --claimOnly` an error occured.

```
root@Ubuntu:~/packtpub-crawler# python script/spider.py -c config/prod.cfg --claimOnly
Traceback (most recent call last):
  File "script/spider.py", line 9, in <module>
    from upload import Upload, SERVICE_GOOGLE_DRIVE, SERVICE_ONEDRIVE, SERVICE_DROPBOX, SERVICE_SCP
  File "/root/packtpub-crawler/script/upload.py", line 1, in <module>
    from googledrive import GoogleDrive
  File "/root/packtpub-crawler/script/googledrive.py", line 3, in <module>
    from oauth2client.client import flow_from_clientsecrets, OOB_CALLBACK_URN
ImportError: No module named oauth2client.client
```

Why? Please give me some advice. Thank you.
P.S. I'm using `Ubuntu 16.04 LTS`. Kernel is `4.13.5-041305-generic`

**Comment by xzl2021** [comment]
`pip install oauth2client==2.2.0` resolved my problem. Thank you.

**Comment by niqdev** [comment]
Great, I suggest anyway to use something like `virtualenv` to avoid this kind of problems
