### ISSUE TITLE
Invalid credentials specified.

### ISSUE THREAD

**Issue by MinhKMA** [niqdev/packtpub-crawler#84]
I'm having this problem, could you help me,pls ? 

```sh
Traceback (most recent call last):
  File "script/spider.py", line 97, in main
    packtpub.runDaily()
  File "/home/minhkma/packtpub-crawler/script/packtpub.py", line 159, in runDaily
    self.__POST_login(loginUrl)
  File "/home/minhkma/packtpub-crawler/script/packtpub.py", line 80, in __POST_login
    raise Exception(error_node.text.strip())
Exception: Invalid credentials specified.
```

**Comment by niqdev** [comment]
Are you credentials correct? `Invalid credentials specified`
If you solve that anyway, it will be blocked by #70
